import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:ren/src/reporter/console_reporter.dart';
import 'package:ren/src/scanner/auto_discovery.dart';

/// The `ren init` command.
///
/// Scans the project, detects the feature structure, and generates ren.yaml.
class InitCommand {
  final String projectPath;

  InitCommand({required this.projectPath});

  Future<void> execute() async {
    ConsolerReporter.printBanner();
    ConsolerReporter.printDivider();
    ConsolerReporter.printInfo('Scanning project structure...');
    print('');

    final discovery = AutoDiscovery(projectPath: projectPath);
    final result = await discovery.discover();

    if (result == null) {
      ConsolerReporter.printError(
        'No lib/ directory found. Is this a Flutter/Dart project?',
      );
      return;
    }

    ConsolerReporter.printSuccess(
      'Detected feature root: ${result.featureRoot}',
    );
    ConsolerReporter.printInfo(
      '${result.features.length} feature(s) found:',
    );

    for (final feature in result.features) {
      print('    · ${feature.name.padRight(20)} ${feature.fileCount} file(s)');
    }

    if (result.ignoredPaths.isNotEmpty) {
      print('');
      ConsolerReporter.printInfo('Suggested ignores:');
      for (final path in result.ignoredPaths) {
        print('    · $path');
      }
    }

    print('');

    final configFile = File(p.join(projectPath, 'ren.yaml'));
    if (configFile.existsSync()) {
      ConsolerReporter.printWarning(
        'ren.yaml already exists — overwrite? (y/N): ',
      );
      stdout.write('  ');
      final input = stdin.readLineSync()?.trim().toLowerCase();
      if (input != 'y') {
        ConsolerReporter.printInfo('Aborted — ren.yaml unchanged.');
        return;
      }
    }

    _generateConfig(configFile, result);

    print('');
    ConsolerReporter.printSuccess('ren.yaml generated at ${configFile.path}');
    ConsolerReporter.printInfo('Run ren to analyze your project.');
    print('');
  }

  void _generateConfig(File file, AutoDiscoveryResult result) {
    final buffer = StringBuffer();
    buffer.writeln('# ren.yaml — Flutter Feature Gravity Analyzer');
    buffer.writeln('# Generated by ren init');
    buffer.writeln('# See https://pub.dev/packages/ren for full docs');
    buffer.writeln('');
    buffer.writeln('# Feature root detected automatically');
    buffer.writeln('features: ${result.featureRoot}');
    buffer.writeln('');
    buffer.writeln('# Fail CI/CD if any feature reaches this level');
    buffer.writeln('# fail_on: high');
    buffer.writeln('');

    if (result.ignoredPaths.isNotEmpty) {
      buffer.writeln('# Paths excluded from analysis');
      buffer.writeln('ignore:');
      for (final path in result.ignoredPaths) {
        buffer.writeln('  - $path');
      }
      buffer.writeln('');
    }

    buffer.writeln('# Override built-in weights (0 = disable rule)');
    buffer.writeln('# weights:');
    buffer.writeln('#   Opacity: 0');
    buffer.writeln('#   BackdropFilter: 60');
    buffer.writeln('');
    buffer.writeln('# Team-specific patterns');
    buffer.writeln('# custom_rules:');
    buffer.writeln('#   - name: MyHeavyWidget');
    buffer.writeln('#     reason: Known to cause jank in production.');
    buffer.writeln('#     weight: 45');

    file.writeAsStringSync(buffer.toString());
  }
}
